project_id = "nycaurobmnnrskwlzgym"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.create-renewal-checkout]
    verify_jwt = false
