project_id = "nycaurobmnnrskwlzgym"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
